// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "b03e6b29-a558-444c-a0bd-366d7b8b68ec";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onFlowChange();
void onLevelChange();

float flow;
float level;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(flow, READWRITE, ON_CHANGE, onFlowChange);
  ArduinoCloud.addProperty(level, READWRITE, ON_CHANGE, onLevelChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
